### ISSUE TITLE
Select fields to display

### ISSUE THREAD

**Issue by zernerj** [RefLex-Team/RefLex-issues#10]
Lorsqu'on souhaite changer les "fields to display", par exemple en supprimant l'affichage de la CGR et en la remplaçant par le COD, une fois qu'on a sauvegardé son choix, tout se réinitialise. En tous cas lorsqu'on l'utilise dans "search in database"

**Comment by IndianaTones** [comment]
@sflavier stp ?

**Comment by GuillaumeSegerer** [comment]
Déjà signalé à Séb il y a longtemps...

**Comment by IndianaTones** [comment]
Seems to be working now? If that was you, merci @sflavier !

**Comment by sflavier** [comment]
ok, je pensais avoir trouvé le bug, et donc la correction fonctionne !!
