### ISSUE TITLE
Customize information in Table

### ISSUE THREAD

**Issue by IndianaTones** [RefLex-Team/RefLex-issues#12]
For languages where the location of the data collection is know, it would be helpful to list the specific villages.

For example, Durieux & Durieux 1998 in Hochstetler (ed) 2004 lists the same language but one cannot see that these languages are spoken in different villages.

**Comment by GuillaumeSegerer** [comment]
This information, when available, is stored in the 'sources' table ('GEO' field). Maybe Seb can make it visible somehow.

**Comment by IndianaTones** [comment]
Yes please!  @sflavier would it be possible to make the sources visible in searches and results?

**Comment by GuillaumeSegerer** [comment]
We don't have much of Seb's time. Maybe you can ask him directly (corrections / additions may receive more attention when sent by researchers and not by me...)

**Comment by sflavier** [comment]
the GEO information can be added on the source information template when using the (i) button.
At this time, we have basic information about the source, WEBBALL and WEB-CAL,  DV fields and com.

we can add the geo information in the right column after the updated date of the source.
<img width="862" alt="Capture d’écran 2023-07-27 à 15 09 12" src="https://github.com/RefLex-Team/RefLex-issues/assets/5690314/e171648e-110c-4c88-a434-7595d994c62c">

Maybe some other fields from the source can be added ? like glottocode of the language of interest in the source ?

**Comment by sflavier** [comment]
information visible with the label "Specific Location" in the previous view for source information.
