### ISSUE TITLE
Onglet Management

### ISSUE THREAD

**Issue by zernerj** [RefLex-Team/RefLex-issues#13]
Quand on clique sur l'onglet management et qu'on clique sur "dataset", s'affichent par défaut nos propres datasets. 
Or la ligne Natural / Public / Own / Shared n'apparaît que si on clique d'abord sur un des éléments de %ABCDEFGH...

**Comment by sflavier** [comment]
Problem solved. the type of dataset in the management can only by own, so the choose is now remove all the time.
correction of some bug in the alpha filter, and added the share button to manage share for different dataset.
