### ISSUE TITLE
Cartographie : custom map

### ISSUE THREAD

**Issue by zernerj** [RefLex-Team/RefLex-issues#18]
- Choix fond de carte : ne change pas quand on change de choix
- Dès lors qu'on fait "edit data" on n'a plus aucun point qui s'affiche et pas de possibilité de revenir en arrière (sauf à fermer le module de customisation)

**Comment by sflavier** [comment]
merci de se référer à la discussion #11 et de compléter les bugs / attentes dans le fil #11
