### ISSUE TITLE
Informations sur un enregistrement

### ISSUE THREAD

**Issue by zernerj** [RefLex-Team/RefLex-issues#19]
Lorsqu'il n'y a pas de pdf, qu'on ait, à la place de "view record in pdf", un genre "view filled fields" qui liste (un champ par ligne) les champs non vides et non calculés.

**Comment by sflavier** [comment]
Un bouton est ajouté. il sera disponible lors de la mise en place de la prochaine version.
il faudrait discuter de la mise en forme de la fiche et des champs précis à afficher.

**Comment by sflavier** [comment]
la mise à jour a été déployé en production
