### ISSUE TITLE
MyST - à fouiller

### ISSUE THREAD

**Issue by zernerj** [RefLex-Team/RefLex-issues#25]
Hello tutti,
Uyen-To a vu passer cet outil "MyST" hier en formation, à fouiller peut-être pour structurer les documentations techniques. Bref, si vous avez le temps de jeter un oeil, on peut en recauser prochainement (ici un exemple : https://gouarin.github.io/python-packaging-2023/structure)

**Comment by sflavier** [comment]
Hello.
malheureusement, le serveur actuel de reflex n'est pas administré par moi, et ne dispose pas à ma connaissance de technologie python, donc je vois pas comment utiliser cet outil.
le serveur doreco que j'administre est lui bien avec du python, mais je n'ai pas eu de réponse d'huma-num sur les possibilité de gérer d'autre sous domaine et d'élargir ses possibilités en augmentant ses capacités (pour acceuillir d'autre projet comme la version clld de reflex par exemple).
