### ISSUE TITLE
Ergonomie plage de navigation liste

### ISSUE THREAD

**Issue by zernerj** [RefLex-Team/RefLex-issues#27]
L'idée est de modifier la séquence <<   <       >   >>, pour que ça puisse faire 0-100 / 101-200 / 201-300 etc, bref, en fonction de la taille de la liste à afficher, proposer des boutons qui permettent d'atteindre directement le milieu de la liste.

**Comment by sflavier** [comment]
au final, conservation de la navigation proche en << < > >>, ajout sur la ligne présentant le nombre de page d'une options pour aller à une page spécifique.
