### ISSUE TITLE
CSS - affichage des 'caddies' de cognate sets

### ISSUE THREAD

**Issue by GuillaumeSegerer** [RefLex-Team/RefLex-issues#36]
Avant, à coté des noms de cognats (dans la recherche sur dataset), deux caddies s'affichaient pour soit ajouter à la sélection, soit remplacer la sélection par le cognate set en question. Depuis peu les caddies étaient apparemment affichés à la ligne du dessous, mais parfois j'arrivais à cliquer sur le petit bout qui dépassait, mais aujourd'hui plus rien
![image](https://github.com/RefLex-Team/RefLex-issues/assets/9321936/d7298a37-0b1c-4b05-8054-0a9a1b14b8f5)

**Comment by sflavier** [comment]
<img width="233" alt="Capture d’écran 2023-12-26 à 11 05 12" src="https://github.com/RefLex-Team/RefLex-issues/assets/5690314/262852ea-1e6f-40ee-b749-0b79370dca99">
de mon côté, en passant le curseur sur le nom, j'ai bien les petit caddy qui apparaissent (sous firefox)

je continue à regarder

**Comment by sflavier** [comment]
ok, le fichier source n'avais pas été mis en place sur le serveur.
normalement ça devrait rentrer dans l'ordre.

**Comment by sflavier** [comment]
voilà, problème normalement résolu, avec affichage en popup des outils/bouton sur la gauche de la colonne Series.
