### ISSUE TITLE
information de sources visibles

### ISSUE THREAD

**Issue by sflavier** [RefLex-Team/RefLex-issues#44]
Dans les choix possible pour les informations de sources, ajouter le nom webcall et le nom glottolog de la langue.
a-t-on déjà les deux en base de données ?

**Comment by GuillaumeSegerer** [comment]
Le nom webcall est (en anglais) dans le champ 'name' de la table `references_langues_base`. Il est aussi en français et en anglais dans la table `references_langues_noms`

**Comment by sflavier** [comment]
ajout de la possiblité de voir le glottocode et le nom webcall de la langue.
par défaut, le nom de langue affiché est celui de la source.
