### ISSUE TITLE
Petits ajustements inferface

### ISSUE THREAD

**Issue by utdr** [RefLex-Team/RefLex-issues#48]
## Généralités
- Ne pas inscrire **"tools panel"** lorsque ça reste vide. 
- Inversion de la sélection : placer juste au dessus des cases à cocher 
- Question : Pourquoi polysémie et homophonie sont dans sources? -> déplacer dans **search in database** 

## Onglets/idiomes cliquables des onglets : 
Data -> `Browse data` 

### Onglet Data 
- Enlever **filter sources** du sous menu et l'intégrer en bas de l'explorateur. Peut-être reformuler les contenus de filter sources pour les béotiens comme nous. 

### Record Set 
- Sauver un **record set** : icône "new" comme pour un cognateset 
- NB : lorsqu'on fusionne deux recordsets, avant enregistrement de la mise à jour, il n'y a pas de drapeau d'état comme pour le dataset, c'est dommage. Avoir la même iconographie que pour le dataset, ça permet d'être moins perdu. 
- Quand on clique sur un recordset, ça ne va pas dans available, mais ça se charge directement en active, par écrasement.

**Comment by sflavier** [comment]
Mise à jours des corrections en ligne.
