### ISSUE TITLE
Prepa Workshop RefLex du 14 sept. 2023

### ISSUE THREAD

**Issue by zernerj** [RefLex-Team/RefLex-issues#9]
Programme pour l'équipe RefLex :
**13/9** : on se retrouve en début d'après-midi à l'Inalco pour tester la démo et ateliers de prise en main RefLex sur le serveur local en prépa du workshop du lendemain.
**14/9** : workshop RefLex prévu de 9H30 à 13H. 
**Programme prévisionnel (commentaires bienvenus):** 
1. Etat des lieux   des données lexicales de référence pour la zone adamawa (Doctorants du domaine)
2. Présentation de la base de données et des outils (GS)
2.a Atelier pratique de prise en main (GS, SF, JZ + UTDR)
3. Enjeux et modalités de saisie et préparation de données pour RefLex - Inventaire des sources prioritaires
3.a Travaux pratiques avec répartition des sources
4. Présentation d'une expérimentation de classification (DI? KP de loin?)
5. Discussions – lancement/suites du projet collaboratif Adamawa-Reflex

**Comment by sflavier** [comment]
Most of the bug encounter during the workshop are now fixed.
- wrong configuration of the cookies, resulting in some user preferences not applied
- when you click on a tag category to see records in this category, if no records, you get the message and not an error.
- when looking for closest language, now the enveloppe is correct.
- when copying an alignement, you can click on it directly to edit it.
- when searching in the database, if extra fields are set for the sources, these fields will be shown.
- Annoying digit shown when an action is taken are now hidden.

a new features is added:
- when settings color and order for a dataset, if extra fields are set for the sources, these fields will be shown.

**Comment by zernerj** [comment]
Ça y est,  tu es passé définitivement à l'anglais? 😊

Bon,  à toute en visio,  pour l'instant je suis passée déposer les surplus de bouffe à Villejuif.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
